#guessing game in Python 3 - needs finishing
print ("Really quick terminal command that you have n't go time to read.."	)
import time #to create delays
time.sleep(0.3)
print ('\n' * 100)
print('.')
time.sleep(0.2)   # delay at start
print('..')
time.sleep(0.2)
print('...')
time.sleep(0.2)
print('....')
time.sleep(0.2)
print('.....')
time.sleep(0.2)
print('......')
time.sleep(0.2)
print('.......')
time.sleep(0.2)
print('........')
time.sleep(0.2)
print('.........')
time.sleep(0.2)
print('..........')
time.sleep(0.2)
print('...........')
time.sleep(0.2)
print('............')
time.sleep(0.2)
print('.............')
time.sleep(0.2)
print('..............')
time.sleep(0.2)
print('...............')
time.sleep(0.2)
print('................')
time.sleep(0.2)
print('')
time.sleep(0.8)
print('Hi')
print('')
time.sleep(0.8)
print('Welcome')
time.sleep(0.8)
print('')
print('Ready to play')
time.sleep(0.8)
print('')
a = int(input("Guess the number: "))
if a == 2:
	time.sleep(1.4)
	print('')
	print('Yep, a does equal 2, mate.                                ' * 50)
	print('')
	time.sleep(1.5)
elif a < 0:
	time.sleep(1.4)
	print('')
	print ('No negative numbers, ta.   	 ' * 50)
	print('')
	time.sleep(1.5)
elif a == 0:
	time.sleep(1.4)
	print('')
	print ('Not zero, try a proper number.     ' *50)
	print('')
	time.sleep(1.5)
elif a == 1:
	time.sleep(1.4)
	print('')
	print ('Think bigger .......  ' * 50)
	print('')
	time.sleep(1.5)
elif a > 2:
	time.sleep(1.4)
	print('')
	print ('Too big |||||  ' * 1000)
	print('')
	time.sleep(1.5)
print ('\n' * 10)
time.sleep(0.4)
print ('                                  Game Over')
time.sleep(1.3)
print ('\n' * 10)
time.sleep(0.4)
print('')
time.sleep(0.8)
print ('         ------------ Run the game again with python3 if.py --------------')
print('')
time.sleep(1.8)
print ('\n' * 10)
time.sleep(0.4)
print('')
print("          *If you're in the terminal press Up key to repeat previous command *")
time.sleep(1.0)
print('')
print ('\n' * 10)
time.sleep(0.4)
time.sleep(0.8)
