def dots():
    print ("Too fast to read.."	)
    import time #to create delays
    time.sleep(0.2)
    print ('\n' * 100) 
    print('.')
    time.sleep(0.2) #delay at start
    print('..')
    time.sleep(0.2)
    print('...')
    time.sleep(0.2)
    print('....')
    time.sleep(0.2)
    print('.....')
    time.sleep(0.2)
    print('......')
    time.sleep(0.2)
    print('.......')
    time.sleep(0.2)
    print('........')
    time.sleep(0.2)
    print('.........')
    time.sleep(0.2)
    print('..........')
    time.sleep(0.2)
    print('...........')
    time.sleep(0.2)
    print('............')
    time.sleep(0.2)
    print('.............')
    time.sleep(0.2)
    print('..............')
    time.sleep(0.2)
    print('...............')
    time.sleep(0.2)
    print('................')
    time.sleep(0.2)
    print('')
    time.sleep(0.8)
#dots()

def dots2(r):
    #print ("Too fast to read.."	)
    import time #to create delays
    time.sleep(r)
    print ('\n' * 100) 
    print('.')
    time.sleep(r) #delay at start
    print('..')
    time.sleep(r)
    print('...')
    time.sleep(r)
    print('....')
    time.sleep(r)
    print('.....')
    time.sleep(r)
    print('......')
    time.sleep(r)
    print('.......')
    time.sleep(r)
    print('........')
    time.sleep(r)
    print('.........')
    time.sleep(r)
    print('..........')
    time.sleep(r)
    print('...........')
    time.sleep(r)
    print('............')
    time.sleep(r)
    print('.............')
    time.sleep(r)
    print('..............')
    time.sleep(r)
    print('...............')
    time.sleep(r)
    print('................')
    time.sleep(r)
    print('')
    time.sleep(r * 4)
#dots2(0.05)

if __name__ == "__main__":
	print("This is just a module file - you will need to run the BPM Converter file in this directory")
